name: Mirror repo to S3
on:
  push:
    branches:
      - master
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: S3 Backup
        uses: ./
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          MIRROR_TARGET: ${{ secrets.S3_MIRROR_TARGET }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          STORAGE_SERVICE_URL: ${{ secrets.S3_STORAGE_SERVICE_URL }}
        with:
          args: --overwrite --remove
